---
references:
- id: 'almeida:2019luz'
  accessed:
    - year: 2020
      month: 3
      day: 4
  author:
    - family: Almeida
      given: Sarah da Silva
    - family: Almeida
      given: Valéria Ribeiro da Silva Franklin
    - family: Lusa
      given: Eduardo Barbosa
  container-title: Anais do 3º Simpósio Científico do ICOMOS Brasil
  event: 3º Simpósio Científico do ICOMOS Brasil
  event-place: Belo Horizonte
  ISBN: 978-85-5722-038-6
  issued:
    - year: 2019
  publisher: IEDS
  publisher-place: Belo Horizonte
  source: www.even3.com.br
  title: >-
    Luz, câmera, preservação! O papel do cinema na conservação da arquitetura
    moderna
  title-short: 'Luz, câmera, preservação!'
  type: paper-conference
  URL: >-
    https://even3.com.br/anais/iiisimposioicomosbrasil/155778-luz-camera-preservacao-o-papel-do-cinema-na-conservacao-da-arquitetura-moderna

- id: 'garcia:2020caixa7'
  accessed:
    - year: 2020
      month: 4
      day: 23
  author:
    - family: Garcia
      given: Cláudia da Conceição
    - family: Josetti Fuensalida
      given: Maria Paz
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
    - family: Silva
      given: Fábio
    - family: Lima
      given: Celso
  container-title: Com Censo
  ISSN: 2359-2494
  issue: '1'
  issued:
    - year: 2020
      month: 3
  language: pt-BR
  page: 100-112
  source: www.periodicos.se.df.gov.br
  title: >-
    A caixa patrimonial: Um projeto de Educação Patrimonial para escolas do
    Distrito Federal
  title-short: A caixa patrimonial
  type: article-journal
  URL: 'http://www.periodicos.se.df.gov.br/index.php/comcenso/article/view/793'
  volume: '7'

- id: 'nascimento:2019imagens13'
  accessed:
    - year: 2020
      month: 4
      day: 24
  author:
    - family: Nascimento
      given: Gledson Rodrigues
  container-title: Domínios da Imagem
  DOI: 10.5433/2237-9126.2019v13n25p116
  ISSN: 2237-9126
  issue: '25'
  issued:
    - year: 2019
  language: pt
  number: '25'
  page: 116-140
  source: www.uel.br
  title: >-
    Imagens fotográficas sobre autoritarismo e manifestações estudantis contra
    os cortes na educação nas cidades de Goiânia e Londrina 15 maio 2019
  type: article-journal
  URL: 'http://www.uel.br/revistas/uel/index.php/dominiosdaimagem/article/view/39913'
  volume: '13'

- id: 'oliveira:2019avenida1'
  accessed:
    - year: 2020
      month: 3
      day: 4
  author:
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
  container-title: Anais eletrônicos...
  event: >-
    Arquisur: Asociación de escuelas y facultades públicas de arquitectura de
    América del Sur
  event-place: 'Belo Horizonte : Campinas'
  ISBN: 978-65-80968-09-1
  issued:
    - year: 2019
  language: pt-br
  page: '112084'
  publisher: Galoá
  publisher-place: 'Belo Horizonte : Campinas'
  source: proceedings.science
  title: 'Avenida Goiás em Goiânia-GO: Perspectivas da Memória Social'
  title-short: Avenida Goiás em Goiânia-GO
  type: paper-conference
  URL: >-
    https://proceedings.science/arquisur-2019/papers/avenida-goias-em-goiania-go--perspectivas-da-memoria-social?lang=pt-br
  volume: '1'

- id: 'oliveira:2019elementos'
  accessed:
    - year: 2020
      month: 3
      day: 4
  author:
    - family: Oliveira
      given: Irina Alencar
      dropping-particle: de
  container-title: 'Anais do 11º mestres e conselheiros: Educação para o patrimônio'
  event: 11º mestres e conselheiros
  event-place: Belo Horizonte
  ISBN: 2176-2783
  issued:
    - year: 2019
  publisher: IEDS
  publisher-place: Belo Horizonte
  source: www.even3.com.br
  title: >-
    Elementos da matriz urbana portuguesa em Goiás: Vila Boa e suas identidades
    culturais
  title-short: Elementos da matriz urbana portuguesa em Goiás
  type: paper-conference
  URL: >-
    https://even3.com.br/anais/11mestreseconselheiros/167873-elementos-da-matriz-urbana-portuguesa-em-goias--vila-boa-e-suas-identidades-culturais

- id: 'palazzo:2018accouplement2'
  accessed:
    - year: 2019
      month: 1
      day: 21
  author:
    - family: Palazzo
      given: Pedro Paulo
  container-title: 'Building knowledge, constructing histories'
  editor:
    - family: Wouters
      given: Ine
    - family: Voorde
      given: Stephanie Van
      dropping-particle: de
    - family: Bertels
      given: Inge
    - family: Espion
      given: Bernard
    - family: Jonge
      given: Krista
      dropping-particle: de
    - family: Zastavni
      given: Denis
  event-place: Leiden
  ISBN: 978-0-429-44675-7
  issued:
    - year: 2018
  language: English
  page: 1029–1036
  publisher: 'CRC : Balkema'
  publisher-place: Leiden
  source: Open WorldCat
  title: 'Accouplement: Vicissitudes of an architectural motif in classical France'
  title-short: Accouplement
  type: chapter
  volume: '2'

- id: 'palazzo:2018tipologia'
  author:
    - family: Palazzo
      given: Pedro Paulo
  container-title: >-
    Um projecto de futuro para a Beirã (Marvão) baseado na arquitectura e
    urbanismo de tradição alentejana = A project for the future of Beirã
    (Marvão) based on the traditional architecture and urbanism of the Alentejo
    region
  editor:
    - family: Hermida
      given: Alejandro García
  event-place: Lisboa
  ISBN: 978-989-98624-6-3
  issued:
    - year: 2018
  language: pt en es
  page: 91–97
  publisher: Fundação Serra Henriques
  publisher-place: Lisboa
  title: >-
    Tipologia da edificação na arquitectura vernácula da Beirã = Building
    typology in the vernacular architecture of Beirã
  title-short: Tipologia da edificação
  type: chapter
  URL: >-
    https://www.premiorafaelmanzano.com/wp-content/uploads/2018/12/Livro_FSH_Marvao-1.pdf

- id: 'palazzo:2019imagem'
  author:
    - family: Palazzo
      given: Pedro Paulo
  event: >-
    Imagem da arquitetura árabe no Brasil. Exposição Alhambras: arquiteturas
    neoárabes em latinoamérica
  event-place: Brasília
  genre: Moderação de mesa-redonda
  issued:
    - year: 2019
      month: 5
      day: 14
  language: pt-br
  publisher-place: Brasília
  title: Imagem da arquitetura árabe no Brasil
  type: speech

- id: 'palazzo:2020relacoes'
  accessed:
    - year: 2020
      month: 3
      day: 17
  author:
    - family: Palazzo
      given: Pedro Paulo
    - family: Solórzano
      given: Gabriel Ernesto Moura
  container-title: 'Paranoá: cadernos de arquitetura e urbanismo'
  container-title-short: Paranoá
  DOI: 10.18830/issn.1679-0944.n25.2020.8
  ISSN: 1679-0944
  issue: '25'
  issued:
    - year: 2020
      month: 3
      day: 14
  language: pt
  number: '25'
  page: 107-128
  source: periodicos.unb.br
  title: 'Relações de escala na superquadra de Brasília: paradigma ou mistificação?'
  title-short: Relações de escala na superquadra de Brasília
  type: article-journal
  URL: 'https://periodicos.unb.br/index.php/paranoa/article/view/29209'

- id: 'pimentellopes:2017especulacao'
  accessed:
    - year: 2020
      month: 3
      day: 4
  author:
    - family: Pimentel Lopes
      given: Camila de Queiroz
  container-title: Anais...
  event: Simpósio Científico Icomos Brasil
  event-place: Belo Horizonte
  ISBN: 978-85-5722-038-6
  issued:
    - year: 2017
  publisher: Instituto Metodista Izabela Hendrix
  publisher-place: Belo Horizonte
  source: www.even3.com.br
  title: >-
    A especulação imobiliária como tentativa de mudança à preservação do
    patrimônio: o caso do bairro Pacaembu em São Paulo
  title-short: >-
    A especulação imobiliária como tentativa de mudança à preservação do
    patrimônio
  type: paper-conference
  URL: >-
    https://even3.com.br/anais/eventosicomos/59619-a-especulacao-imobiliaria-como-tentativa-de-mudanca-a-preservacao-do-patrimonio---o-caso-do-bairro-pacaembu-em-sao

- id: 'pimentellopes:2018bases'
  accessed:
    - year: 2020
      month: 3
      day: 5
  author:
    - family: Pimentel Lopes
      given: Camila de Queiroz
  container-title: 'PNUM 2018. A Produção do Território: Formas, Processos, Desígnios'
  editor:
    - family: Calix
      given: Teresa
    - family: Fernandes
      given: Ana Silva
    - family: Sucena
      given: Sara
    - family: Travasso
      given: Nuno
    - family: Moreira
      given: Bruno
  event: Portuguese Network of Urban Morphology
  event-place: Porto
  ISBN: 978-989-8527-21-9
  issued:
    - year: 2018
  page: 2291-2303
  publisher: Faculdade de Arquitetura da Universidade do Porto
  publisher-place: Porto
  title: Bases conceituais da morfologia urbana
  type: paper-conference
  URL: 'https://pnum.arq.up.pt/wp-content/uploads/docs/PNUM2018_ACTAS_v3.13.pdf'

- id: 'pimentellopes:2018natividade'
  accessed:
    - year: 2020
      month: 3
      day: 4
  author:
    - family: Pimentel Lopes
      given: Camila de Queiroz
  container-title: Anais do 5º Seminário Ibero-americano Arquitetura e Documentação
  event: 5º Seminário Ibero-americano Arquitetura e Documentação
  event-place: Belo Horizonte
  ISBN: 2237-5619
  issued:
    - year: 2018
  publisher: 'UFMG : Even3'
  publisher-place: Belo Horizonte
  source: www.even3.com.br
  title: 'Natividade – Tocantins: Registros de sua História'
  title-short: Natividade
  type: paper-conference
  URL: >-
    https://even3.com.br/anais/arqdoc/71115-natividade--tocantins--registros-de-sua-historia

- id: 'solorzano:2019relacoes'
  author:
    - family: Solórzano
      given: Gabriel Ernesto Moura
    - family: Palazzo
      given: Pedro Paulo
  container-title: Anais
  event: XVIII Enanpur
  event-place: Natal
  ISBN: 1984-8781
  issued:
    - year: 2019
  publisher-place: Natal
  title: 'Relações de escala na superquadra de Brasília: paradigma ouu mistificação?'
  title-short: Relações de escala na superquadra de Brasília
  type: paper-conference
  URL: 'http://anpur.org.br/xviiienanpur/anaisadmin/capapdf.php?reqid=972'
...
